In [17]:
import numpy as np

data = np.zeros((3,4))

data

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
data = np.ones((3,4))

data

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
print(np.empty((3,4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [27]:
my_array = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(my_array.shape)

my_array.size

(2, 4)


8

In [49]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a / b)

[0.25 0.4  0.5 ]


In [53]:
print(np.sin(a))

[0.84147098 0.90929743 0.14112001]


In [59]:
marks = np.array([30, 40, 50, 60, 70, 80, 90, 100])
print(marks[0:5:1])
print(marks[1:-1:2])

[30 40 50 60 70]
[40 60 80]
